name: BugBank CI

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: yarn cypress run

jobs: 
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3.5.3

      - name: install dependencies
        run: yarn install

      - name: Run e2e tests
        run: ${{ github.event.inputs.cli }}

      
